language: go

go:
  - "1.14"

before_script:
  # For mixin
  - go install github.com/monitoring-mixins/mixtool/cmd/mixtool
  - go install github.com/google/go-jsonnet/cmd/jsonnetfmt

script:
  - diff -u <(echo -n) <(gofmt -s -d ./)
  - diff -u <(echo -n) <(go vet ./...)
  - go test -v ./...
  - make -C github-mixin lint build

env:
  - GO111MODULE=on
